### ISSUE TITLE
SSL: WRONG_VERSION_NUMBER

### ISSUE THREAD

**Issue by HerrDoktorBD** [declension/squeeze-alexa#6]
I'm hung at the stunnel connectivity step.  Feel free to delete this issue and/or respond directly to me on github.  Thanks!

I've replaced my server name with my-server to protect the innocent.

On my-server:
Stunnel configuration:
```
root@my-server:/etc/init# cat /opt/etc/stunnel/stunnel.conf 
; Sample stunnel configuration file by Michal Trojnara 2002-2005
; Some options used here may not be adequate for your particular configuration
; Please make sure you understand them (especially the effect of chroot jail)

; Certificate/key is needed in server mode and optional in client mode
cert = /opt/etc/stunnel/stunnel.pem
;key = /opt/etc/stunnel/stunnel.pem

; Some security enhancements for UNIX systems - comment them out on Win32
chroot = /opt/var/stunnel/
setuid = nobody
setgid = nobody
; PID is created inside chroot jail
pid = /stunnel.pid

; Some performance tunings
socket = l:TCP_NODELAY=1
socket = r:TCP_NODELAY=1
;compression = rle

; Workaround for Eudora bug
;options = DONT_INSERT_EMPTY_FRAGMENTS

; Authentication stuff
;verify = 2
; Don't forget to c_rehash CApath;  CApath is located inside chroot jail:
;CApath = /certs
; It's often easier to use CAfile:
;CAfile = /opt/etc/stunnel/certs.pem
; Don't forget to c_rehash CRLpath;  CRLpath is located inside chroot jail:
;CRLpath = /crls
; Alternatively you can use CRLfile:
;CRLfile = /opt/etc/stunnel/crls.pem

; Some debugging stuff useful for troubleshooting
;debug = 7
;output = stunnel.log

; Use it for client mode
;client = yes

; Service-level configuration

[pop3s]
accept  = 995
connect = 110

[imaps]
accept  = 993
connect = 143

[ssmtp]
accept  = 465
connect = 25

;[https]
;accept  = 443
;connect = 80
;TIMEOUTclose = 0

; vim:ft=dosini

[slim]
accept = 9002
connect = my-server.synology.me:9002

verify = 3
CAfile = /opt/etc/stunnel/stunnel.pem
cert = /opt/etc/stunnel/stunnel.pem
TIMEOUTclose = 0
```
Stunnel installation status:
```
root@my-server:/etc/init# sudo ipkg status stunnel
Package: stunnel
Version: 4.26-2
Depends: openssl, zlib, psmisc
Status: install user installed
Architecture: i686
Installed-Time: 1490381796
Successfully terminated.
```
Looks like the stunnel installation went OK.
Stunnel service status:
```
root@my-server:/etc/init# ps -aux | grep stunnel
nobody   13097  0.0  0.0   4208   336 ?        Ss   Mar24   0:00 /opt/sbin/stunnel
root     22614  0.0  0.0  23124   968 pts/9    S+   08:53   0:00 grep --color=auto stunnel
```
Looks like the stunnel service is running.

On my mac:
```
tonys-mbp:squeeze-alexa-master tony$ openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout key.pem -out cert.pem -subj "/CN=my-server.synology.me" -days 3650
Generating a 2048 bit RSA private key
......................+++
.........................................+++
writing new private key to 'key.pem'
-----
tonys-mbp:squeeze-alexa-master tony$ cat cert.pem key.pem > squeeze-alexa.pem && rm -f key.pem
tonys-mbp:squeeze-alexa-master tony$ ls
HOWTO.md		bin			lambda.json		squeeze-alexa.pem
LICENSE			cert.pem		metadata		squeezealexa
README.md		handler.py		requirements.txt	tests
```
Finally, check connectivity:
```
tonys-mbp:squeeze-alexa-master tony$ python bin/local_test.py
Couldn't connect to my-server.synology.me:9002 with TLS
Traceback (most recent call last):
  File "bin/local_test.py", line 28, in <module>
    verify_hostname=VERIFY_SERVER_HOSTNAME)
  File "squeezealexa/ssl_wrap.py", line 57, in __init__
    self._ssl_sock.connect((hostname, port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 844, in connect
    self._real_connect(addr, False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 835, in _real_connect
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: WRONG_VERSION_NUMBER] wrong version number (_ssl.c:590)
```

What should I do to fix this error?

Thanks and best regards,

Tony

**Comment by declension** [comment]
Hi. Are you sure you want to proxy port 9002? 

The proxying is of the [CLI (telnet) protocol](http://wiki.slimdevices.com/index.php/Logitech_Media_Server_CLI) not the web interface (which is not SSL on that port IIRC, hence the error I suspect).

Essentially: try changing that `9002` to `9090`

**Comment by HerrDoktorBD** [comment]
Sorry, I forgot to mention that I changed the default port from 9000 to 9002 when I installed LMS.  My router's firewall lets this port get through.  On my phone, I can reach the player with:

`my-server.synology.me:9002`

What needs to be done with the 9090 and where?

Here is the settings.py file:
```
tonys-mbp:squeezealexa tony$ cat settings.py
# -*- coding: utf-8 -*-
#
#   Copyright 2017 Nick Boultbee
#   This file is part of squeeze-alexa.
#
#   squeeze-alexa is free software: you can redistribute it and/or modify
#   it under the terms of the GNU General Public License as published by
#   the Free Software Foundation, either version 3 of the License, or
#   (at your option) any later version.
#
#   See LICENSE for full license

from os.path import dirname, join

"""
This file contains settings with everything set to the defaults
At the very least you need to set SERVER_HOSTNAME, SERVER_PORT and CERT_FILE.
"""


# --------------------------- Amazon / Alexa Config ---------------------------

APPLICATION_ID = None
"""The Skill's Amazon application ID (e.g. amznl.ask.skill.xyz...) as a string
A value of None means verification of the request's Skill will be disabled.
"""

RESPONSE_AUDIO_FILE_URL = \
    "https://s3.amazonaws.com/declension-alexa-media/silence.mp3"
"""Change this to your own HTTPS MP3 file, which must be accessible to Alexa"""

# ----------------------------- Squeezebox Config -----------------------------

SERVER_HOSTNAME = 'my-server.synology.me'
"""The public hostname / IP of your Squeezebox server CLI proxy"""

SERVER_PORT = 9002
"""The above server's port"""

SERVER_USERNAME = None
"""A string containing the Squeezebox CLI username, or None if not required."""

SERVER_PASSWORD = None
"""A string containing the Squeezebox CLI password, or None if not required."""

DEFAULT_PLAYER = None
"""The default Squeezebox player ID (long MAC-like string) to use"""


# ------------------------- TLS (SSL) Configuration ---------------------------

CERT_FILE = 'squeeze-alexa.pem'
"""The PEM-format certificate filename for TLS verification,
or None to disable"""

CERT_FILE_PATH = (join(dirname(dirname(__file__)), CERT_FILE)
                  if CERT_FILE else None)
"""The full path to the certificate file"""

CA_FILE_PATH = CERT_FILE_PATH
"""The certificate authority file, in .pem.
This can be the same as the CERT_FILE_PATH if you're self-certifying."""

VERIFY_SERVER_HOSTNAME = bool(CERT_FILE_PATH)
"""Whether to verify the server's TLS certificate hostname.
Override to False if your certificate is for a different domain than your
SERVER_HOSTNAME."""
tonys-mbp:squeezealexa tony$ 
```
Cheers.

**Comment by HerrDoktorBD** [comment]
Oh, I get it.  9090 is for the CLI not the web interface (read msg fully...).  Let me try poking a hole in the firewall for 9090 and change the settings to 9090 as you suggested.

**Comment by declension** [comment]
BTW I assume you intended to expose the IMAPS, SSMTP etc for other usage...

**Comment by HerrDoktorBD** [comment]
Ehm, I did not.

Here's what I get now:

```
tonys-mbp:squeeze-alexa-master tony$ python bin/local_test.py
Couldn't connect to my-server.synology.me:9090 with TLS
Traceback (most recent call last):
  File "bin/local_test.py", line 28, in <module>
    verify_hostname=VERIFY_SERVER_HOSTNAME)
  File "squeezealexa/ssl_wrap.py", line 57, in __init__
    self._ssl_sock.connect((hostname, port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 844, in connect
    self._real_connect(addr, False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 835, in _real_connect
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
ssl.SSLError: [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:590)
```

**Comment by HerrDoktorBD** [comment]
Could this be the cause?

```
Error binding slim to 0.0.0.0:9090
bind: Address already in use (98)
```
Stunnel error log:
```
root@my-server:/opt/etc/stunnel# cat stunnel.log
2017.03.28 11:38:27 LOG7[13118:4147463936]: RAND_status claims sufficient entropy for the PRNG
2017.03.28 11:38:27 LOG7[13118:4147463936]: PRNG seeded successfully
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: Key file: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Private key loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: SSL context initialized for service pop3s
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: Key file: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Private key loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: SSL context initialized for service imaps
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: Key file: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Private key loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: SSL context initialized for service ssmtp
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Certificate loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: Key file: /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Private key loaded
2017.03.28 11:38:27 LOG7[13118:4147463936]: Loaded verify certificates from /opt/etc/stunnel/stunnel.pem
2017.03.28 11:38:27 LOG7[13118:4147463936]: Loaded /opt/etc/stunnel/stunnel.pem revocation lookup file
2017.03.28 11:38:27 LOG7[13118:4147463936]: SSL context initialized for service slim
2017.03.28 11:38:27 LOG5[13118:4147463936]: stunnel 4.26 on i686-pc-linux-gnu with OpenSSL 0.9.8v 19 Apr 2012
2017.03.28 11:38:27 LOG5[13118:4147463936]: Threading:PTHREAD SSL:ENGINE Sockets:POLL,IPv6 Auth:LIBWRAP
2017.03.28 11:38:27 LOG6[13118:4147463936]: file ulimit = 1024 (can be changed with 'ulimit -n')
2017.03.28 11:38:27 LOG6[13118:4147463936]: poll() used - no FD_SETSIZE limit for file descriptors
2017.03.28 11:38:27 LOG5[13118:4147463936]: 500 clients allowed
2017.03.28 11:38:27 LOG7[13118:4147463936]: FD 10 in non-blocking mode
2017.03.28 11:38:27 LOG7[13118:4147463936]: FD 11 in non-blocking mode
2017.03.28 11:38:27 LOG7[13118:4147463936]: FD 12 in non-blocking mode
2017.03.28 11:38:27 LOG7[13118:4147463936]: SO_REUSEADDR option set on accept socket
2017.03.28 11:38:27 LOG7[13118:4147463936]: pop3s bound to 0.0.0.0:995
2017.03.28 11:38:27 LOG7[13118:4147463936]: FD 13 in non-blocking mode
2017.03.28 11:38:27 LOG7[13118:4147463936]: SO_REUSEADDR option set on accept socket
2017.03.28 11:38:27 LOG7[13118:4147463936]: imaps bound to 0.0.0.0:993
2017.03.28 11:38:27 LOG7[13118:4147463936]: FD 14 in non-blocking mode
2017.03.28 11:38:27 LOG7[13118:4147463936]: SO_REUSEADDR option set on accept socket
2017.03.28 11:38:27 LOG7[13118:4147463936]: ssmtp bound to 0.0.0.0:465
2017.03.28 11:38:27 LOG7[13118:4147463936]: FD 15 in non-blocking mode
2017.03.28 11:38:27 LOG7[13118:4147463936]: SO_REUSEADDR option set on accept socket
2017.03.28 11:38:27 LOG3[13118:4147463936]: Error binding slim to 0.0.0.0:9090
2017.03.28 11:38:27 LOG3[13118:4147463936]: bind: Address already in use (98)
```

**Comment by declension** [comment]
Yes - it won't have much luck if that port's already in use. 
Two options:
 * Find out what's on that port (e.g. `netstat -tln4`), and either kill it (it's probably an earlier instance of `stunnel`) and try again, or:
 * you can (maybe even should) choose a different (and less common) port for your NAS server to listen on e.g. `19090`.

The actual problem now is probably what's in your `/opt/etc/stunnel/stunnel.pem` - is it the same as the `squeeze-alexa.pem`? Actually it doesn't _have_ to be, but it gets a lot more complicated if not...

Meanwhile I'd delete the config from `; Service-level configuration` up to just before the `[slim]`, to stop exposing those services.

**Comment by HerrDoktorBD** [comment]
I'm sorry this is becoming such a long thread.  It was indeed an earlier instance of stunnel.  After killing it and restarting a new instance, we have:
```
root@my-server:~# netstat -tlp4
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       PID/Program name    
tcp        0      0 0.0.0.0:9090            0.0.0.0:*               LISTEN      16834/stunnel       
tcp        0      0 0.0.0.0:printer         0.0.0.0:*               LISTEN      15656/inetd         
tcp        0      0 0.0.0.0:54244           0.0.0.0:*               LISTEN      13649/statd         
etc...
```
So now, here's the python version:
```
tonys-mbp:squeeze-alexa-master tony$ python --version
Python 2.7.10
```
generate the key:
```
tonys-mbp:squeeze-alexa-master tony$ openssl req -x509 -newkey rsa:2048 -sha256 -nodes -keyout key.pem -out cert.pem -subj "/CN=my-server.synology.me" -days 3650
Generating a 2048 bit RSA private key
.................................+++
.....................................+++
writing new private key to 'key.pem'
-----
tonys-mbp:squeeze-alexa-master tony$ cat cert.pem key.pem > squeeze-alexa.pem && rm -f key.pem
```
and finally test the connection:
```
tonys-mbp:squeeze-alexa-master tony$ python bin/local_test.py
Traceback (most recent call last):
  File "bin/local_test.py", line 28, in <module>
    verify_hostname=VERIFY_SERVER_HOSTNAME)
  File "squeezealexa/ssl_wrap.py", line 57, in __init__
    self._ssl_sock.connect((hostname, port))
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 844, in connect
    self._real_connect(addr, False)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 835, in _real_connect
    self.do_handshake()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/ssl.py", line 808, in do_handshake
    self._sslobj.do_handshake()
socket.error: [Errno 54] Connection reset by peer
tonys-mbp:squeeze-alexa-master tony$ 
```
I suspect we're getting close but still no cigar.

**Comment by declension** [comment]
@HerrDoktorBD no worries.
Yes, think that's closer now. The other end is hanging up, probably wrong cert i.e. failing authentication. I'm pushing some doc updates to clarify as I think that was overlooked when I documented.

If you prefer, try https://gitter.im/squeeze-alexa/Lobby which is now up and running

**Comment by declension** [comment]
(solved eventually). 

Some documentation updates, diagrams, improvements and clarifications pushed along the way, as well as some [adding some automated diagnostics](https://github.com/declension/squeeze-alexa/commit/14d4e7441eda7948bdcbe9cb397a0e62b32aa43e).

https://github.com/declension/squeeze-alexa/blob/master/HOWTO.md
